// ═══════════════════════════════════════════════════════════════
// PAGEFORGE v2 — Prebuilt Template Library
// Each template is a complete ThemeEditorConfig ready to load
// into the Zustand store with one click.
// ═══════════════════════════════════════════════════════════════

import type { ThemeSection, NavItemConfig, FooterColumn, SocialLink } from '@/lib/wp-theme-generator';

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────

export type TemplateCategory =
  | 'business'
  | 'portfolio'
  | 'blog'
  | 'ecommerce'
  | 'saas'
  | 'restaurant'
  | 'medical'
  | 'education'
  | 'realestate'
  | 'legal';

export interface TemplateMeta {
  id: string;
  name: string;
  category: TemplateCategory;
  description: string;
  badge?: string;         // e.g. "Popular", "Nuevo"
  sections: ThemeSection[];
  navItems: NavItemConfig[];
  footerColumns: FooterColumn[];
  copyrightText: string;
  socialLinks: SocialLink[];
  // Design tokens
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  headingFont: string;
  bodyFont: string;
  borderRadius: number;
  // Metadata
  themeName: string;
  themeSlug: string;
  themeDescription: string;
}

// ─────────────────────────────────────────────────────────────
// Category metadata
// ─────────────────────────────────────────────────────────────

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string; emoji: string; count: number }[] = [
  { id: 'business', label: 'Business / Corporate', emoji: '🏢', count: 2 },
  { id: 'portfolio', label: 'Portfolio', emoji: '📸', count: 2 },
  { id: 'blog', label: 'Blog / Magazine', emoji: '📝', count: 2 },
  { id: 'ecommerce', label: 'E-Commerce', emoji: '🛒', count: 2 },
  { id: 'saas', label: 'SaaS / Tech', emoji: '💻', count: 2 },
  { id: 'restaurant', label: 'Restaurant / Food', emoji: '🍽️', count: 1 },
  { id: 'medical', label: 'Medical / Health', emoji: '🏥', count: 1 },
  { id: 'education', label: 'Education / LMS', emoji: '🎓', count: 1 },
  { id: 'realestate', label: 'Real Estate', emoji: '🏠', count: 1 },
  { id: 'legal', label: 'Lawyer / Legal', emoji: '⚖️', count: 1 },
];

// ─────────────────────────────────────────────────────────────
// Helper: create sections from config
// ─────────────────────────────────────────────────────────────

function s(type: ThemeSection['type'], title: string, subtitle: string, data: Record<string, any>): ThemeSection {
  return { type, enabled: true, title, subtitle, data };
}

// ═══════════════════════════════════════════════════════════════
// TEMPLATE DEFINITIONS
// ═══════════════════════════════════════════════════════════════

const templates: TemplateMeta[] = [
  // ─── BUSINESS / CORPORATE ─────────────────────────────────
  {
    id: 'business-pro',
    name: 'Business Pro',
    category: 'business',
    description: 'Sitio corporativo profesional con hero impactante, servicios, equipo, testimonios y CTA. Ideal para empresas medianas y grandes.',
    badge: 'Popular',
    primaryColor: '#1B4332',
    secondaryColor: '#2D6A4F',
    accentColor: '#D4A373',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    headingFont: 'Montserrat',
    bodyFont: 'Open Sans',
    borderRadius: 8,
    themeName: 'Business Pro',
    themeSlug: 'business-pro',
    themeDescription: 'Professional corporate WordPress theme generated by PageForge',
    sections: [
      s('hero', 'Impulsa Tu Negocio al Siguiente Nivel', 'Soluciones digitales integrales para empresas que buscan crecer', {
        title: 'Impulsa Tu Negocio al Siguiente Nivel',
        subtitle: 'Soluciones digitales integrales para empresas que buscan crecer',
        ctaText: 'Solicitar Propuesta',
        ctaLink: '#contact',
        secondaryCtaText: 'Nuestros Servicios',
        secondaryCtaLink: '#services',
        backgroundImage: '/templates/hero-business-pro.png',
        overlayOpacity: 0.65,
      }),
      s('services', 'Nuestros Servicios', 'Ofrecemos soluciones completas para tu empresa', {
        title: 'Nuestros Servicios',
        subtitle: 'Ofrecemos soluciones completas para tu empresa',
        items: [
          { icon: '📊', title: 'Consultoría Estratégica', description: 'Análisis profundo de tu negocio para identificar oportunidades de crecimiento y optimización.' },
          { icon: '💻', title: 'Desarrollo Web', description: 'Sitios web modernos, rápidos y optimizados para conversión.' },
          { icon: '📱', title: 'Marketing Digital', description: 'Estrategias de SEO, SEM y redes sociales para maximizar tu alcance.' },
          { icon: '🔒', title: 'Ciberseguridad', description: 'Protección integral de datos y sistemas contra amenazas digitales.' },
          { icon: '☁️', title: 'Cloud Solutions', description: 'Infraestructura en la nube escalable y segura para tu operación.' },
          { icon: '🤖', title: 'Inteligencia Artificial', description: 'Automatización y análisis inteligente para tomar mejores decisiones.' },
        ],
        columns: 3,
      }),
      s('about', 'Sobre Nosotros', 'Más de 15 años de experiencia transformando negocios', {
        title: 'Sobre Nosotros',
        subtitle: 'Más de 15 años de experiencia transformando negocios',
        image: '/templates/about-business-pro.png',
        stats: [
          { value: '500+', label: 'Clientes Satisfechos' },
          { value: '15+', label: 'Años de Experiencia' },
          { value: '98%', label: 'Tasa de Retención' },
          { value: '50+', label: 'Expertos en el Equipo' },
        ],
      }),
      s('stats', '', '', {
        items: [
          { icon: '🏆', value: '200+', label: 'Proyectos Completados' },
          { icon: '🌍', value: '12', label: 'Países Atendidos' },
          { icon: '⭐', value: '4.9/5', label: 'Calificación Promedio' },
          { icon: '🚀', value: '99.9%', label: 'Uptime Garantizado' },
        ],
      }),
      s('testimonials', 'Lo Que Dicen Nuestros Clientes', 'Historias de éxito de empresas que confiaron en nosotros', {
        title: 'Lo Que Dicen Nuestros Clientes',
        subtitle: 'Historias de éxito de empresas que confiaron en nosotros',
        testimonials: [
          { quote: 'Business Pro transformó completamente nuestra presencia digital. Nuestro tráfico web aumentó un 300% en solo 6 meses.', name: 'María García', role: 'CEO, TechStart', rating: 5 },
          { quote: 'El equipo es increíblemente profesional. Entregaron el proyecto antes del plazo y superó todas nuestras expectativas.', name: 'Carlos Rodríguez', role: 'Director de Marketing, InnovaGroup', rating: 5 },
          { quote: 'Gracias a sus soluciones de marketing digital, nuestras ventas online se duplicaron en el primer trimestre.', name: 'Ana Martínez', role: 'Fundadora, E-Shop Pro', rating: 5 },
        ],
      }),
      s('team', 'Nuestro Equipo', 'Profesionales apasionados por lo que hacen', {
        title: 'Nuestro Equipo',
        subtitle: 'Profesionales apasionados por lo que hacen',
        members: [
          { name: 'Roberto Sánchez', role: 'CEO & Fundador', bio: 'Más de 20 años liderando proyectos tecnológicos innovadores.', avatar: '/templates/avatar-business-1.png', socials: [{ platform: 'linkedin', url: '#' }] },
          { name: 'Laura Fernández', role: 'Directora de Operaciones', bio: 'Experta en optimización de procesos empresariales.', avatar: '/templates/avatar-business-2.png', socials: [{ platform: 'linkedin', url: '#' }] },
          { name: 'Diego Morales', role: 'CTO', bio: 'Arquitecto de software con experiencia en sistemas de gran escala.', avatar: '/templates/avatar-business-3.png', socials: [{ platform: 'linkedin', url: '#' }] },
        ],
      }),
      s('cta', '¿Listo Para Transformar Tu Empresa?', 'Agenda una consulta gratuita y descubre cómo podemos ayudarte', {
        title: '¿Listo Para Transformar Tu Empresa?',
        subtitle: 'Agenda una consulta gratuita y descubre cómo podemos ayudarte',
        ctaText: 'Agendar Consulta Gratuita',
        ctaLink: '#contact',
      }),
      s('contact', 'Contáctanos', 'Estamos listos para escucharte', {
        title: 'Contáctanos',
        subtitle: 'Estamos listos para escucharte',
        email: 'info@businesspro.com',
        phone: '+1 (555) 123-4567',
        address: 'Av. Reforma 250, Col. Juárez, CDMX, México',
        showForm: true,
      }),
    ],
    navItems: [
      { label: 'Inicio', url: '/' },
      { label: 'Servicios', url: '#services' },
      { label: 'Nosotros', url: '#about' },
      { label: 'Equipo', url: '#team' },
      { label: 'Contacto', url: '#contact' },
    ],
    footerColumns: [
      { title: 'Empresa', links: [{ label: 'Sobre Nosotros', url: '#about' }, { label: 'Nuestro Equipo', url: '#team' }, { label: 'Carreras', url: '#' }] },
      { title: 'Servicios', links: [{ label: 'Consultoría', url: '#services' }, { label: 'Desarrollo Web', url: '#services' }, { label: 'Marketing Digital', url: '#services' }] },
      { title: 'Recursos', links: [{ label: 'Blog', url: '/blog' }, { label: 'Casos de Éxito', url: '#' }, { label: 'FAQ', url: '#' }] },
      { title: 'Contacto', links: [{ label: 'Ubicación', url: '#contact' }, { label: 'Email', url: '#contact' }, { label: 'Teléfono', url: '#contact' }] },
    ],
    copyrightText: 'Business Pro. Todos los derechos reservados.',
    socialLinks: [
      { platform: 'linkedin', url: '#' },
      { platform: 'twitter', url: '#' },
      { platform: 'facebook', url: '#' },
      { platform: 'instagram', url: '#' },
    ],
  },
  {
    id: 'startup-hub',
    name: 'Startup Hub',
    category: 'business',
    description: 'Diseño moderno y audaz para startups tecnológicas. Landing page optimizada para conversión con secciones de features, pricing y testimonios.',
    badge: 'Nuevo',
    primaryColor: '#7C3AED',
    secondaryColor: '#4F46E5',
    accentColor: '#F59E0B',
    backgroundColor: '#FFFFFF',
    textColor: '#111827',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    borderRadius: 12,
    themeName: 'Startup Hub',
    themeSlug: 'startup-hub',
    themeDescription: 'Modern startup landing page WordPress theme by PageForge',
    sections: [
      s('hero', 'Build Something Amazing Today', 'The all-in-one platform that helps startups launch faster, grow smarter, and scale effortlessly.', {
        title: 'Build Something Amazing Today',
        subtitle: 'The all-in-one platform that helps startups launch faster, grow smarter, and scale effortlessly.',
        ctaText: 'Start Free Trial',
        ctaLink: '#pricing',
        secondaryCtaText: 'Watch Demo',
        secondaryCtaLink: '#',
        backgroundImage: '/templates/hero-startup-hub.png',
        overlayOpacity: 0.7,
      }),
      s('features', 'Everything You Need to Succeed', 'Powerful features designed to accelerate your growth', {
        title: 'Everything You Need to Succeed',
        subtitle: 'Powerful features designed to accelerate your growth',
        items: [
          { icon: '⚡', title: 'Lightning Fast', description: 'Sub-second load times. Your users never wait.' },
          { icon: '🛡️', title: 'Enterprise Security', description: 'SOC 2 compliant with end-to-end encryption.' },
          { icon: '📈', title: 'Analytics Built-in', description: 'Real-time dashboards to track every metric that matters.' },
          { icon: '🔌', title: '200+ Integrations', description: 'Connect with Slack, Stripe, HubSpot, and more.' },
          { icon: '🤖', title: 'AI-Powered', description: 'Smart automation that learns from your workflow.' },
          { icon: '🌍', title: 'Global CDN', description: 'Serve content from 50+ edge locations worldwide.' },
        ],
        columns: 3,
      }),
      s('testimonials', 'Loved by Founders Worldwide', 'Join 5,000+ startups already growing with us', {
        title: 'Loved by Founders Worldwide',
        subtitle: 'Join 5,000+ startups already growing with us',
        testimonials: [
          { quote: 'We cut our development time by 60% using this platform. Absolutely game-changing for our team.', name: 'Sarah Chen', role: 'CTO, LaunchPad', rating: 5 },
          { quote: 'The analytics alone saved us $50K/year on separate tools. Best ROI we\'ve ever seen.', name: 'Marcus Johnson', role: 'CEO, GrowthLoop', rating: 5 },
          { quote: 'From MVP to Series A in 8 months. This platform was our unfair advantage.', name: 'Priya Patel', role: 'Founder, NexGen AI', rating: 5 },
        ],
      }),
      s('pricing', 'Simple, Transparent Pricing', 'No hidden fees. Scale as you grow.', {
        title: 'Simple, Transparent Pricing',
        subtitle: 'No hidden fees. Scale as you grow.',
        plans: [
          { name: 'Starter', price: '$0', period: '/month', features: ['Up to 1,000 users', '5 GB storage', 'Basic analytics', 'Community support'], highlighted: false, ctaText: 'Get Started Free' },
          { name: 'Growth', price: '$49', period: '/month', features: ['Up to 50,000 users', '100 GB storage', 'Advanced analytics', 'Priority support', 'Custom domain', 'API access'], highlighted: true, ctaText: 'Start Growing' },
          { name: 'Scale', price: '$199', period: '/month', features: ['Unlimited users', '1 TB storage', 'Enterprise analytics', 'Dedicated support', 'SLA guarantee', 'Custom integrations', 'SSO/SAML'], highlighted: false, ctaText: 'Talk to Sales' },
        ],
      }),
      s('faq', 'Frequently Asked Questions', 'Everything you need to know', {
        title: 'Frequently Asked Questions',
        subtitle: 'Everything you need to know',
        items: [
          { question: 'Is there a free plan?', answer: 'Yes! Our Starter plan is completely free with no credit card required. Upgrade anytime as you grow.' },
          { question: 'Can I cancel anytime?', answer: 'Absolutely. No contracts, no cancellation fees. You can cancel your subscription at any time from your dashboard.' },
          { question: 'Do you offer custom enterprise plans?', answer: 'Yes, we offer tailored solutions for enterprise clients. Contact our sales team for a custom quote.' },
          { question: 'What kind of support do you offer?', answer: 'Community support for Starter, priority email support for Growth, and dedicated account management for Scale plans.' },
        ],
      }),
      s('cta', 'Ready to Launch?', 'Start building your startup today — no credit card required', {
        title: 'Ready to Launch?',
        subtitle: 'Start building your startup today — no credit card required',
        ctaText: 'Start Free Trial',
        ctaLink: '#pricing',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Features', url: '#features' },
      { label: 'Pricing', url: '#pricing' },
      { label: 'FAQ', url: '#faq' },
    ],
    footerColumns: [
      { title: 'Product', links: [{ label: 'Features', url: '#features' }, { label: 'Pricing', url: '#pricing' }, { label: 'Integrations', url: '#' }, { label: 'Changelog', url: '#' }] },
      { title: 'Company', links: [{ label: 'About', url: '#' }, { label: 'Blog', url: '/blog' }, { label: 'Careers', url: '#' }] },
      { title: 'Resources', links: [{ label: 'Documentation', url: '#' }, { label: 'API Reference', url: '#' }, { label: 'Community', url: '#' }] },
      { title: 'Legal', links: [{ label: 'Privacy Policy', url: '#' }, { label: 'Terms of Service', url: '#' }] },
    ],
    copyrightText: 'Startup Hub. All rights reserved.',
    socialLinks: [
      { platform: 'twitter', url: '#' },
      { platform: 'linkedin', url: '#' },
      { platform: 'github', url: '#' },
    ],
  },

  // ─── PORTFOLIO ─────────────────────────────────────────────
  {
    id: 'portfolio-creative',
    name: 'Portfolio Creative',
    category: 'portfolio',
    description: 'Portafolio elegante y minimalista para fotógrafos, diseñadores y artistas. Galería de proyectos destacados con contacto integrado.',
    badge: 'Popular',
    primaryColor: '#1F2937',
    secondaryColor: '#6B7280',
    accentColor: '#EC4899',
    backgroundColor: '#FAFAFA',
    textColor: '#1F2937',
    headingFont: 'Playfair Display',
    bodyFont: 'Lato',
    borderRadius: 4,
    themeName: 'Portfolio Creative',
    themeSlug: 'portfolio-creative',
    themeDescription: 'Elegant portfolio WordPress theme for creatives by PageForge',
    sections: [
      s('hero', 'Creative Vision. Real Impact.', 'Award-winning design portfolio showcasing bold ideas and beautiful execution.', {
        title: 'Creative Vision. Real Impact.',
        subtitle: 'Award-winning design portfolio showcasing bold ideas and beautiful execution.',
        ctaText: 'Ver Proyectos',
        ctaLink: '#gallery',
        secondaryCtaText: 'Contacto',
        secondaryCtaLink: '#contact',
        backgroundImage: '/templates/hero-portfolio-creative.png',
        overlayOpacity: 0.6,
      }),
      s('about', 'About Me', 'Designer & Creative Director with 10+ years of experience crafting digital experiences', {
        title: 'About Me',
        subtitle: 'Designer & Creative Director with 10+ years of experience crafting digital experiences',
        image: '/templates/about-portfolio-creative.png',
        stats: [
          { value: '150+', label: 'Proyectos' },
          { value: '12', label: 'Premios' },
          { value: '8+', label: 'Años' },
          { value: '80+', label: 'Clientes' },
        ],
      }),
      s('gallery', 'Selected Work', 'A curated collection of my best projects across branding, web, and digital', {
        title: 'Selected Work',
        subtitle: 'A curated collection of my best projects across branding, web, and digital',
        images: [
          { src: '/templates/gallery-creative-1.png', alt: 'Brand Identity Project', caption: 'Brand Identity — Luxe Fashion' },
          { src: '/templates/gallery-creative-2.png', alt: 'Web Design Project', caption: 'Web Design — TechVault App' },
          { src: '/templates/gallery-creative-3.png', alt: 'UI/UX Project', caption: 'UI/UX — FinFlow Dashboard' },
          { src: '/templates/gallery-creative-4.png', alt: 'Print Design Project', caption: 'Print — Artisan Coffee Co.' },
          { src: '/templates/gallery-creative-5.png', alt: 'Photography Project', caption: 'Photography — Urban Series' },
          { src: '/templates/gallery-creative-6.png', alt: 'Packaging Project', caption: 'Packaging — Organic Skincare' },
        ],
        columns: 3,
      }),
      s('services', 'What I Do', 'Specialized services tailored to elevate your brand', {
        title: 'What I Do',
        subtitle: 'Specialized services tailored to elevate your brand',
        items: [
          { icon: '🎨', title: 'Brand Identity', description: 'Complete visual identity systems including logos, color palettes, and brand guidelines.' },
          { icon: '🖥️', title: 'Web Design', description: 'Responsive, pixel-perfect websites that convert visitors into customers.' },
          { icon: '📱', title: 'UI/UX Design', description: 'User-centered interfaces for web and mobile applications.' },
          { icon: '📷', title: 'Photography', description: 'Professional photography for products, events, and editorial.' },
        ],
        columns: 2,
      }),
      s('testimonials', 'Client Testimonials', 'Words from people I\'ve had the pleasure of working with', {
        title: 'Client Testimonials',
        subtitle: 'Words from people I\'ve had the pleasure of working with',
        testimonials: [
          { quote: 'Working with this designer completely transformed our brand. The attention to detail and creative vision exceeded all expectations.', name: 'James Mitchell', role: 'Founder, Luxe Fashion', rating: 5 },
          { quote: 'The most talented and professional designer I\'ve ever worked with. Delivered ahead of schedule with exceptional quality.', name: 'Sophie Laurent', role: 'CMO, TechVault', rating: 5 },
        ],
      }),
      s('contact', 'Let\'s Work Together', 'Have a project in mind? I\'d love to hear about it.', {
        title: 'Let\'s Work Together',
        subtitle: 'Have a project in mind? I\'d love to hear about it.',
        email: 'hello@creativeportfolio.com',
        phone: '+1 (555) 987-6543',
        address: 'Brooklyn, New York, USA',
        showForm: true,
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Work', url: '#gallery' },
      { label: 'About', url: '#about' },
      { label: 'Services', url: '#services' },
      { label: 'Contact', url: '#contact' },
    ],
    footerColumns: [
      { title: 'Navigation', links: [{ label: 'Work', url: '#gallery' }, { label: 'About', url: '#about' }, { label: 'Services', url: '#services' }, { label: 'Contact', url: '#contact' }] },
      { title: 'Social', links: [{ label: 'Instagram', url: '#' }, { label: 'Behance', url: '#' }, { label: 'Dribbble', url: '#' }, { label: 'LinkedIn', url: '#' }] },
    ],
    copyrightText: 'Portfolio Creative. All rights reserved.',
    socialLinks: [
      { platform: 'instagram', url: '#' },
      { platform: 'linkedin', url: '#' },
      { platform: 'twitter', url: '#' },
    ],
  },
  {
    id: 'portfolio-architect',
    name: 'Architecture Studio',
    category: 'portfolio',
    description: 'Portafolio sofisticado para estudios de arquitectura e interiorismo. Grid visual impactante con secciones de proceso y servicios.',
    primaryColor: '#292524',
    secondaryColor: '#78716C',
    accentColor: '#D97706',
    backgroundColor: '#FFFBF5',
    textColor: '#292524',
    headingFont: 'Raleway',
    bodyFont: 'Source Sans Pro',
    borderRadius: 2,
    themeName: 'Architecture Studio',
    themeSlug: 'architecture-studio',
    themeDescription: 'Sophisticated architecture portfolio WordPress theme by PageForge',
    sections: [
      s('hero', 'Designing Spaces That Inspire', 'Award-winning architecture & interior design studio creating meaningful environments since 2008', {
        title: 'Designing Spaces That Inspire',
        subtitle: 'Award-winning architecture & interior design studio creating meaningful environments since 2008',
        ctaText: 'View Projects',
        ctaLink: '#gallery',
        secondaryCtaText: 'Our Approach',
        secondaryCtaLink: '#about',
        backgroundImage: '/templates/hero-portfolio-architect.png',
        overlayOpacity: 0.55,
      }),
      s('about', 'Our Philosophy', 'We believe architecture should serve both people and place, creating harmony between form and function', {
        title: 'Our Philosophy',
        subtitle: 'We believe architecture should serve both people and place, creating harmony between form and function',
        image: '/templates/about-portfolio-architect.png',
        stats: [
          { value: '120+', label: 'Projects Completed' },
          { value: '16', label: 'Years Experience' },
          { value: '8', label: 'Design Awards' },
          { value: '3', label: 'International Offices' },
        ],
      }),
      s('gallery', 'Featured Projects', 'Selected works from residential, commercial, and cultural commissions', {
        title: 'Featured Projects',
        subtitle: 'Selected works from residential, commercial, and cultural commissions',
        images: [
          { src: '/templates/gallery-arch-1.png', alt: 'Modern Villa Project', caption: 'Casa Lumina — Modern Villa' },
          { src: '/templates/gallery-arch-2.png', alt: 'Office Tower Project', caption: 'Vertex Tower — Corporate HQ' },
          { src: '/templates/gallery-arch-3.png', alt: 'Museum Project', caption: 'Museum of Modern Arts — Gallery Wing' },
          { src: '/templates/gallery-arch-4.png', alt: 'Restaurant Interior', caption: 'Noma Restaurant — Interior Design' },
        ],
        columns: 2,
      }),
      s('services', 'Our Services', 'Comprehensive design services from concept to completion', {
        title: 'Our Services',
        subtitle: 'Comprehensive design services from concept to completion',
        items: [
          { icon: '📐', title: 'Architectural Design', description: 'Full-service architectural design from initial concept through construction documentation.' },
          { icon: '🏠', title: 'Interior Design', description: 'Bespoke interior spaces that reflect our clients\' unique vision and lifestyle.' },
          { icon: '🌆', title: 'Urban Planning', description: 'Master planning and urban design for sustainable, livable communities.' },
          { icon: '🔄', title: 'Renovation', description: 'Sensitive restoration and adaptive reuse of existing structures.' },
        ],
        columns: 2,
      }),
      s('cta', 'Start Your Project', 'Let\'s create something extraordinary together', {
        title: 'Start Your Project',
        subtitle: 'Let\'s create something extraordinary together',
        ctaText: 'Schedule a Consultation',
        ctaLink: '#contact',
      }),
      s('contact', 'Get In Touch', 'We\'d love to discuss your next project', {
        title: 'Get In Touch',
        subtitle: 'We\'d love to discuss your next project',
        email: 'studio@architectstudio.com',
        phone: '+1 (555) 234-5678',
        address: '450 Park Avenue, New York, NY 10022',
        showForm: true,
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Projects', url: '#gallery' },
      { label: 'About', url: '#about' },
      { label: 'Services', url: '#services' },
      { label: 'Contact', url: '#contact' },
    ],
    footerColumns: [
      { title: 'Studio', links: [{ label: 'About', url: '#about' }, { label: 'Team', url: '#' }, { label: 'Careers', url: '#' }] },
      { title: 'Projects', links: [{ label: 'Residential', url: '#' }, { label: 'Commercial', url: '#' }, { label: 'Cultural', url: '#' }] },
      { title: 'Contact', links: [{ label: 'Email', url: '#contact' }, { label: 'Phone', url: '#contact' }, { label: 'Location', url: '#contact' }] },
    ],
    copyrightText: 'Architecture Studio. All rights reserved.',
    socialLinks: [
      { platform: 'instagram', url: '#' },
      { platform: 'linkedin', url: '#' },
      { platform: 'facebook', url: '#' },
    ],
  },

  // ─── BLOG / MAGAZINE ───────────────────────────────────────
  {
    id: 'blog-personal',
    name: 'Personal Blog',
    category: 'blog',
    description: 'Blog personal limpio y enfocado en la lectura. Tipografía elegante, secciones de featured posts y suscripción por email.',
    badge: 'Popular',
    primaryColor: '#059669',
    secondaryColor: '#0D9488',
    accentColor: '#F97316',
    backgroundColor: '#FFFFFF',
    textColor: '#374151',
    headingFont: 'Merriweather',
    bodyFont: 'Lato',
    borderRadius: 6,
    themeName: 'Personal Blog',
    themeSlug: 'personal-blog',
    themeDescription: 'Clean personal blog WordPress theme by PageForge',
    sections: [
      s('hero', 'Stories, Ideas & Reflections', 'A personal blog about technology, design, and the creative process', {
        title: 'Stories, Ideas & Reflections',
        subtitle: 'A personal blog about technology, design, and the creative process',
        ctaText: 'Read the Blog',
        ctaLink: '#posts',
        secondaryCtaText: 'Subscribe',
        secondaryCtaLink: '#cta',
        backgroundImage: '/templates/hero-blog-minimal.png',
        overlayOpacity: 0.5,
      }),
      s('features', 'What I Write About', 'Exploring ideas at the intersection of technology, design, and life', {
        title: 'What I Write About',
        subtitle: 'Exploring ideas at the intersection of technology, design, and life',
        items: [
          { icon: '💻', title: 'Technology', description: 'Deep dives into software development, AI, and emerging technologies.' },
          { icon: '🎨', title: 'Design', description: 'UI/UX trends, design systems, and creative problem solving.' },
          { icon: '💡', title: 'Productivity', description: 'Tools, habits, and frameworks for doing your best work.' },
        ],
        columns: 3,
      }),
      s('blog_posts', 'Latest Posts', 'Recently published articles', {
        title: 'Latest Posts',
        subtitle: 'Recently published articles',
      }),
      s('testimonials', 'Reader Feedback', 'What readers say about this blog', {
        title: 'Reader Feedback',
        subtitle: 'What readers say about this blog',
        testimonials: [
          { quote: 'One of the most thoughtful tech blogs I\'ve found. Every article is worth reading.', name: 'David Park', role: 'Software Engineer', rating: 5 },
          { quote: 'The design insights here have genuinely improved my work. Subscribed for life.', name: 'Emma Wilson', role: 'Product Designer', rating: 5 },
        ],
      }),
      s('cta', 'Subscribe to My Newsletter', 'Get new articles delivered to your inbox every week. No spam, ever.', {
        title: 'Subscribe to My Newsletter',
        subtitle: 'Get new articles delivered to your inbox every week. No spam, ever.',
        ctaText: 'Subscribe Now',
        ctaLink: '#',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Blog', url: '/blog' },
      { label: 'About', url: '#about' },
      { label: 'Subscribe', url: '#cta' },
    ],
    footerColumns: [
      { title: 'Categories', links: [{ label: 'Technology', url: '#' }, { label: 'Design', url: '#' }, { label: 'Productivity', url: '#' }] },
      { title: 'Links', links: [{ label: 'About', url: '#about' }, { label: 'Archive', url: '#' }, { label: 'RSS Feed', url: '#' }] },
      { title: 'Social', links: [{ label: 'Twitter', url: '#' }, { label: 'LinkedIn', url: '#' }, { label: 'GitHub', url: '#' }] },
    ],
    copyrightText: 'Personal Blog. All rights reserved.',
    socialLinks: [
      { platform: 'twitter', url: '#' },
      { platform: 'linkedin', url: '#' },
      { platform: 'instagram', url: '#' },
    ],
  },
  {
    id: 'magazine-news',
    name: 'News Magazine',
    category: 'blog',
    description: 'Magazine de noticias moderno con diseño editorial. Grid de contenido, categorías, y secciones de artículos destacados.',
    primaryColor: '#DC2626',
    secondaryColor: '#1F2937',
    accentColor: '#2563EB',
    backgroundColor: '#F9FAFB',
    textColor: '#111827',
    headingFont: 'Oswald',
    bodyFont: 'Roboto',
    borderRadius: 4,
    themeName: 'News Magazine',
    themeSlug: 'news-magazine',
    themeDescription: 'Modern news magazine WordPress theme by PageForge',
    sections: [
      s('hero', 'Breaking News & In-Depth Analysis', 'Your trusted source for the latest stories, investigative journalism, and expert opinions', {
        title: 'Breaking News & In-Depth Analysis',
        subtitle: 'Your trusted source for the latest stories, investigative journalism, and expert opinions',
        ctaText: 'Read Latest',
        ctaLink: '#posts',
        secondaryCtaText: 'Categories',
        secondaryCtaLink: '#',
        backgroundImage: '/templates/hero-blog-lifestyle.png',
        overlayOpacity: 0.6,
      }),
      s('features', 'Topics We Cover', 'Comprehensive coverage across multiple categories', {
        title: 'Topics We Cover',
        subtitle: 'Comprehensive coverage across multiple categories',
        items: [
          { icon: '🌍', title: 'World News', description: 'Breaking stories and analysis from around the globe.' },
          { icon: '💰', title: 'Business & Finance', description: 'Market updates, economic policy, and investment insights.' },
          { icon: '🔬', title: 'Science & Tech', description: 'Innovation, discoveries, and the future of technology.' },
          { icon: '🎨', title: 'Culture & Arts', description: 'Entertainment, music, film, and cultural commentary.' },
          { icon: '⚽', title: 'Sports', description: 'Live scores, analysis, and exclusive interviews.' },
          { icon: '🏥', title: 'Health & Wellness', description: 'Medical breakthroughs, fitness, and mental health.' },
        ],
        columns: 3,
      }),
      s('blog_posts', 'Latest Articles', 'Stay informed with our latest journalism', {
        title: 'Latest Articles',
        subtitle: 'Stay informed with our latest journalism',
      }),
      s('stats', 'Our Impact', '', {
        items: [
          { icon: '📰', value: '10K+', label: 'Articles Published' },
          { icon: '👁️', value: '2M+', label: 'Monthly Readers' },
          { icon: '🏆', value: '15', label: 'Journalism Awards' },
          { icon: '✍️', value: '50+', label: 'Contributors' },
        ],
      }),
      s('cta', 'Never Miss a Story', 'Subscribe to our daily newsletter for the latest news delivered to your inbox', {
        title: 'Never Miss a Story',
        subtitle: 'Subscribe to our daily newsletter for the latest news delivered to your inbox',
        ctaText: 'Subscribe Free',
        ctaLink: '#',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'World', url: '#' },
      { label: 'Business', url: '#' },
      { label: 'Tech', url: '#' },
      { label: 'Sports', url: '#' },
      { label: 'Culture', url: '#' },
    ],
    footerColumns: [
      { title: 'Sections', links: [{ label: 'World', url: '#' }, { label: 'Business', url: '#' }, { label: 'Technology', url: '#' }, { label: 'Sports', url: '#' }] },
      { title: 'More', links: [{ label: 'Culture', url: '#' }, { label: 'Health', url: '#' }, { label: 'Opinion', url: '#' }, { label: 'Video', url: '#' }] },
      { title: 'About', links: [{ label: 'Our Team', url: '#' }, { label: 'Careers', url: '#' }, { label: 'Contact', url: '#' }, { label: 'Advertise', url: '#' }] },
    ],
    copyrightText: 'News Magazine. All rights reserved.',
    socialLinks: [
      { platform: 'twitter', url: '#' },
      { platform: 'facebook', url: '#' },
      { platform: 'instagram', url: '#' },
      { platform: 'youtube', url: '#' },
    ],
  },

  // ─── E-COMMERCE ────────────────────────────────────────────
  {
    id: 'ecommerce-fashion',
    name: 'Fashion Store',
    category: 'ecommerce',
    description: 'Tienda de moda elegante con estética premium. Secciones de productos destacados, categorías, testimonios de clientes.',
    badge: 'Popular',
    primaryColor: '#1F2937',
    secondaryColor: '#92400E',
    accentColor: '#B91C1C',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    headingFont: 'Poppins',
    bodyFont: 'Open Sans',
    borderRadius: 0,
    themeName: 'Fashion Store',
    themeSlug: 'fashion-store',
    themeDescription: 'Premium fashion e-commerce WordPress theme by PageForge',
    sections: [
      s('hero', 'New Season Collection', 'Discover timeless elegance with our curated selection of premium fashion', {
        title: 'New Season Collection',
        subtitle: 'Discover timeless elegance with our curated selection of premium fashion',
        ctaText: 'Shop Now',
        ctaLink: '#',
        secondaryCtaText: 'View Lookbook',
        secondaryCtaLink: '#gallery',
        backgroundImage: '/templates/hero-ecommerce-fashion.png',
        overlayOpacity: 0.45,
      }),
      s('features', 'Why Shop With Us', 'An exceptional shopping experience from browsing to delivery', {
        title: 'Why Shop With Us',
        subtitle: 'An exceptional shopping experience from browsing to delivery',
        items: [
          { icon: '🚚', title: 'Free Shipping', description: 'Complimentary shipping on all orders over $100.' },
          { icon: '↩️', title: 'Easy Returns', description: '30-day hassle-free return policy on all items.' },
          { icon: '🔒', title: 'Secure Payment', description: 'Your data is protected with bank-level encryption.' },
          { icon: '💎', title: 'Premium Quality', description: 'Every piece is crafted with the finest materials.' },
        ],
        columns: 4,
      }),
      s('gallery', 'Featured Products', 'Highlights from our latest collections', {
        title: 'Featured Products',
        subtitle: 'Highlights from our latest collections',
        images: [
          { src: '/templates/gallery-creative-1.png', alt: 'Silk Blouse', caption: 'Silk Blouse — $189' },
          { src: '/templates/gallery-creative-2.png', alt: 'Wool Coat', caption: 'Wool Coat — $450' },
          { src: '/templates/gallery-creative-3.png', alt: 'Leather Bag', caption: 'Leather Tote — $320' },
          { src: '/templates/gallery-creative-4.png', alt: 'Cashmere Sweater', caption: 'Cashmere Sweater — $275' },
          { src: '/templates/gallery-creative-5.png', alt: 'Denim Collection', caption: 'Premium Denim — $165' },
          { src: '/templates/gallery-creative-6.png', alt: 'Accessories', caption: 'Gold Accessories — $95' },
        ],
        columns: 3,
      }),
      s('testimonials', 'What Our Customers Say', 'Real reviews from real fashion lovers', {
        title: 'What Our Customers Say',
        subtitle: 'Real reviews from real fashion lovers',
        testimonials: [
          { quote: 'The quality is absolutely stunning. Every piece I\'ve ordered has exceeded my expectations. This is now my go-to fashion destination.', name: 'Isabella Romano', role: 'Verified Buyer', rating: 5 },
          { quote: 'Fast shipping, beautiful packaging, and the clothes fit perfectly. What more could you ask for?', name: 'Charlotte Nguyen', role: 'Verified Buyer', rating: 5 },
          { quote: 'Their customer service is exceptional. They helped me find the perfect outfit for a special occasion.', name: 'Victoria Hayes', role: 'Verified Buyer', rating: 5 },
        ],
      }),
      s('cta', 'Join Our VIP Club', 'Get 15% off your first order plus exclusive early access to new collections', {
        title: 'Join Our VIP Club',
        subtitle: 'Get 15% off your first order plus exclusive early access to new collections',
        ctaText: 'Join Now — It\'s Free',
        ctaLink: '#',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Shop', url: '#' },
      { label: 'Collections', url: '#' },
      { label: 'About', url: '#' },
      { label: 'Contact', url: '#' },
    ],
    footerColumns: [
      { title: 'Shop', links: [{ label: 'New Arrivals', url: '#' }, { label: 'Best Sellers', url: '#' }, { label: 'Sale', url: '#' }, { label: 'Gift Cards', url: '#' }] },
      { title: 'Help', links: [{ label: 'Shipping Info', url: '#' }, { label: 'Returns', url: '#' }, { label: 'Size Guide', url: '#' }, { label: 'FAQ', url: '#' }] },
      { title: 'Company', links: [{ label: 'Our Story', url: '#' }, { label: 'Sustainability', url: '#' }, { label: 'Careers', url: '#' }] },
    ],
    copyrightText: 'Fashion Store. All rights reserved.',
    socialLinks: [
      { platform: 'instagram', url: '#' },
      { platform: 'facebook', url: '#' },
      { platform: 'twitter', url: '#' },
      { platform: 'youtube', url: '#' },
    ],
  },
  {
    id: 'ecommerce-electronics',
    name: 'Tech Store',
    category: 'ecommerce',
    description: 'Tienda de electrónica con diseño moderno y tech. Categorías de productos, especificaciones técnicas y soporte.',
    primaryColor: '#0F172A',
    secondaryColor: '#1E40AF',
    accentColor: '#06B6D4',
    backgroundColor: '#FFFFFF',
    textColor: '#0F172A',
    headingFont: 'Inter',
    bodyFont: 'Roboto',
    borderRadius: 8,
    themeName: 'Tech Store',
    themeSlug: 'tech-store',
    themeDescription: 'Modern electronics e-commerce WordPress theme by PageForge',
    sections: [
      s('hero', 'Next-Gen Tech at Your Fingertips', 'The latest gadgets, electronics, and smart devices — curated for tech enthusiasts', {
        title: 'Next-Gen Tech at Your Fingertips',
        subtitle: 'The latest gadgets, electronics, and smart devices — curated for tech enthusiasts',
        ctaText: 'Shop Now',
        ctaLink: '#',
        secondaryCtaText: 'View Deals',
        secondaryCtaLink: '#',
        backgroundImage: '/templates/hero-ecommerce-tech.png',
        overlayOpacity: 0.7,
      }),
      s('features', 'Why Choose Us', 'The best tech shopping experience', {
        title: 'Why Choose Us',
        subtitle: 'The best tech shopping experience',
        items: [
          { icon: '⚡', title: 'Latest Products', description: 'We stock the newest releases from top brands.' },
          { icon: '✅', title: 'Authenticity Guaranteed', description: '100% genuine products with full manufacturer warranty.' },
          { icon: '📦', title: 'Fast Delivery', description: 'Same-day dispatch and express shipping options.' },
          { icon: '🛡️', title: 'Extended Warranty', description: 'Optional extended warranty on all electronics.' },
        ],
        columns: 4,
      }),
      s('gallery', 'Featured Products', 'Top picks from our catalog', {
        title: 'Featured Products',
        subtitle: 'Top picks from our catalog',
        images: [
          { src: '/templates/gallery-arch-1.png', alt: 'Wireless Earbuds', caption: 'ProSound AirPods — $149' },
          { src: '/templates/gallery-arch-2.png', alt: 'Smart Watch', caption: 'UltraWatch Series 8 — $399' },
          { src: '/templates/gallery-arch-3.png', alt: 'Laptop', caption: 'ProBook 16" M3 — $1,499' },
          { src: '/templates/gallery-arch-4.png', alt: 'Wireless Speaker', caption: 'SoundMax 360 — $299' },
          { src: '/templates/gallery-creative-1.png', alt: 'Drone', caption: 'SkyView Pro 4K — $899' },
          { src: '/templates/gallery-creative-2.png', alt: 'Camera', caption: 'PixelShot Mark IV — $2,499' },
        ],
        columns: 3,
      }),
      s('testimonials', 'Customer Reviews', 'What tech lovers say about us', {
        title: 'Customer Reviews',
        subtitle: 'What tech lovers say about us',
        testimonials: [
          { quote: 'Best online tech store I\'ve found. Genuine products, great prices, and incredibly fast shipping.', name: 'Alex Kim', role: 'Verified Buyer', rating: 5 },
          { quote: 'Their customer support actually knows about tech. Helped me choose the right laptop for my needs.', name: 'Jordan Mills', role: 'Verified Buyer', rating: 5 },
        ],
      }),
      s('faq', 'FAQ & Support', 'Answers to common questions', {
        title: 'FAQ & Support',
        subtitle: 'Answers to common questions',
        items: [
          { question: 'Do you offer international shipping?', answer: 'Yes! We ship to over 50 countries worldwide with tracked delivery.' },
          { question: 'What is your return policy?', answer: 'We offer a 30-day return policy for all unused items in original packaging.' },
          { question: 'Are all products covered by warranty?', answer: 'Yes, all products come with the full manufacturer warranty. Extended warranties are also available.' },
        ],
      }),
      s('cta', 'Sign Up for Tech Deals', 'Get exclusive discounts and early access to new product launches', {
        title: 'Sign Up for Tech Deals',
        subtitle: 'Get exclusive discounts and early access to new product launches',
        ctaText: 'Subscribe Free',
        ctaLink: '#',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Shop', url: '#' },
      { label: 'Deals', url: '#' },
      { label: 'Support', url: '#' },
    ],
    footerColumns: [
      { title: 'Categories', links: [{ label: 'Audio', url: '#' }, { label: 'Wearables', url: '#' }, { label: 'Laptops', url: '#' }, { label: 'Cameras', url: '#' }] },
      { title: 'Support', links: [{ label: 'Help Center', url: '#' }, { label: 'Track Order', url: '#' }, { label: 'Returns', url: '#' }, { label: 'Warranty', url: '#' }] },
      { title: 'Company', links: [{ label: 'About Us', url: '#' }, { label: 'Careers', url: '#' }, { label: 'Blog', url: '#' }] },
    ],
    copyrightText: 'Tech Store. All rights reserved.',
    socialLinks: [
      { platform: 'twitter', url: '#' },
      { platform: 'facebook', url: '#' },
      { platform: 'instagram', url: '#' },
      { platform: 'youtube', url: '#' },
    ],
  },

  // ─── SAAS / TECH ───────────────────────────────────────────
  {
    id: 'saas-app',
    name: 'SaaS Landing',
    category: 'saas',
    description: 'Landing page para producto SaaS con diseño limpio. Features, pricing, integraciones, testimonios y CTA de trial gratuito.',
    primaryColor: '#2563EB',
    secondaryColor: '#7C3AED',
    accentColor: '#10B981',
    backgroundColor: '#FFFFFF',
    textColor: '#111827',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    borderRadius: 8,
    themeName: 'SaaS Landing',
    themeSlug: 'saas-landing',
    themeDescription: 'Modern SaaS landing page WordPress theme by PageForge',
    sections: [
      s('hero', 'The Smart Way to Manage Your Business', 'All-in-one platform for project management, team collaboration, and business analytics', {
        title: 'The Smart Way to Manage Your Business',
        subtitle: 'All-in-one platform for project management, team collaboration, and business analytics',
        ctaText: 'Start Free Trial',
        ctaLink: '#pricing',
        secondaryCtaText: 'Watch Demo',
        secondaryCtaLink: '#',
        backgroundImage: '/templates/hero-saas-platform.png',
        overlayOpacity: 0.6,
      }),
      s('features', 'Powerful Features', 'Everything you need to run your business efficiently', {
        title: 'Powerful Features',
        subtitle: 'Everything you need to run your business efficiently',
        items: [
          { icon: '📋', title: 'Project Management', description: 'Kanban boards, Gantt charts, and timeline views to manage every project.' },
          { icon: '👥', title: 'Team Collaboration', description: 'Real-time chat, file sharing, and collaborative document editing.' },
          { icon: '📊', title: 'Analytics Dashboard', description: 'Customizable dashboards with real-time KPIs and automated reports.' },
          { icon: '🔗', title: '200+ Integrations', description: 'Connect with Slack, GitHub, Jira, Salesforce, and hundreds more.' },
          { icon: '⏱️', title: 'Time Tracking', description: 'Built-in time tracker with automatic timesheet generation.' },
          { icon: '🎯', title: 'Goal Setting', description: 'OKRs and KPIs tracking to align team objectives with business goals.' },
        ],
        columns: 3,
      }),
      s('stats', 'Trusted by Teams Everywhere', '', {
        items: [
          { icon: '🏢', value: '10,000+', label: 'Companies' },
          { icon: '👥', value: '500K+', label: 'Users' },
          { icon: '⭐', value: '4.8/5', label: 'Rating' },
          { icon: '🌍', value: '120+', label: 'Countries' },
        ],
      }),
      s('testimonials', 'What Teams Are Saying', 'Real feedback from teams using our platform', {
        title: 'What Teams Are Saying',
        subtitle: 'Real feedback from teams using our platform',
        testimonials: [
          { quote: 'This platform replaced 5 different tools for us. Our team productivity increased by 40% in the first month.', name: 'Jennifer Wu', role: 'VP Engineering, DataCorp', rating: 5 },
          { quote: 'The best project management tool we\'ve ever used. Intuitive, powerful, and the integrations are seamless.', name: 'Tomás Rivera', role: 'CTO, ScaleUp Inc.', rating: 5 },
          { quote: 'Onboarding our entire team took less than a day. The learning curve is practically zero.', name: 'Emily Zhang', role: 'Head of Operations, FlowState', rating: 5 },
        ],
      }),
      s('pricing', 'Simple Pricing', 'Plans for every team size', {
        title: 'Simple Pricing',
        subtitle: 'Plans for every team size',
        plans: [
          { name: 'Free', price: '$0', period: '/month', features: ['Up to 5 users', '3 projects', 'Basic analytics', 'Community support'], highlighted: false, ctaText: 'Get Started' },
          { name: 'Pro', price: '$29', period: '/user/month', features: ['Unlimited users', 'Unlimited projects', 'Advanced analytics', 'Priority support', 'Integrations', 'Time tracking'], highlighted: true, ctaText: 'Start Free Trial' },
          { name: 'Enterprise', price: 'Custom', period: '', features: ['Everything in Pro', 'SSO/SAML', 'Custom API', 'Dedicated CSM', 'SLA', 'On-premise option'], highlighted: false, ctaText: 'Contact Sales' },
        ],
      }),
      s('faq', 'FAQ', 'Common questions answered', {
        title: 'FAQ',
        subtitle: 'Common questions answered',
        items: [
          { question: 'Is there a free plan?', answer: 'Yes! Our free plan includes up to 5 users and 3 projects with no time limit.' },
          { question: 'Can I switch plans anytime?', answer: 'Absolutely. You can upgrade, downgrade, or cancel at any time. Changes take effect immediately.' },
          { question: 'Is my data secure?', answer: 'We use AES-256 encryption, are SOC 2 Type II certified, and perform regular security audits.' },
          { question: 'Do you offer discounts for nonprofits?', answer: 'Yes! We offer 50% off for registered nonprofits and educational institutions.' },
        ],
      }),
      s('cta', 'Start Your Free Trial Today', 'Join 10,000+ teams already using our platform. No credit card required.', {
        title: 'Start Your Free Trial Today',
        subtitle: 'Join 10,000+ teams already using our platform. No credit card required.',
        ctaText: 'Get Started Free',
        ctaLink: '#pricing',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Features', url: '#features' },
      { label: 'Pricing', url: '#pricing' },
      { label: 'FAQ', url: '#faq' },
    ],
    footerColumns: [
      { title: 'Product', links: [{ label: 'Features', url: '#features' }, { label: 'Pricing', url: '#pricing' }, { label: 'Integrations', url: '#' }, { label: 'Changelog', url: '#' }] },
      { title: 'Company', links: [{ label: 'About', url: '#' }, { label: 'Blog', url: '#' }, { label: 'Careers', url: '#' }] },
      { title: 'Resources', links: [{ label: 'Documentation', url: '#' }, { label: 'API', url: '#' }, { label: 'Status', url: '#' }] },
      { title: 'Legal', links: [{ label: 'Privacy', url: '#' }, { label: 'Terms', url: '#' }, { label: 'Security', url: '#' }] },
    ],
    copyrightText: 'SaaS Landing. All rights reserved.',
    socialLinks: [
      { platform: 'twitter', url: '#' },
      { platform: 'linkedin', url: '#' },
      { platform: 'github', url: '#' },
    ],
  },
  {
    id: 'dev-tools',
    name: 'Dev Tools',
    category: 'saas',
    description: 'Landing page para herramientas de desarrolladores. Estilo dark/tech con features técnicas, documentación y pricing.',
    primaryColor: '#10B981',
    secondaryColor: '#6366F1',
    accentColor: '#F59E0B',
    backgroundColor: '#0F172A',
    textColor: '#E2E8F0',
    headingFont: 'JetBrains Mono',
    bodyFont: 'Inter',
    borderRadius: 6,
    themeName: 'Dev Tools',
    themeSlug: 'dev-tools',
    themeDescription: 'Developer tools landing page WordPress theme by PageForge',
    sections: [
      s('hero', 'Ship Better Code, Faster', 'CLI tools, APIs, and SDKs that make developers 10x more productive', {
        title: 'Ship Better Code, Faster',
        subtitle: 'CLI tools, APIs, and SDKs that make developers 10x more productive',
        ctaText: 'Get Started Free',
        ctaLink: '#pricing',
        secondaryCtaText: 'View on GitHub',
        secondaryCtaLink: '#',
        backgroundImage: '/templates/hero-saas-marketing.png',
        overlayOpacity: 0.7,
      }),
      s('features', 'Built for Developers', 'Tools designed by developers, for developers', {
        title: 'Built for Developers',
        subtitle: 'Tools designed by developers, for developers',
        items: [
          { icon: '⚡', title: 'Lightning CLI', description: 'Build, test, and deploy with a single command. Zero config needed.' },
          { icon: '🔌', title: 'Universal API', description: 'RESTful and GraphQL APIs with automatic client generation in 10+ languages.' },
          { icon: '🧪', title: 'Auto Testing', description: 'AI-powered test generation with 95%+ coverage out of the box.' },
          { icon: '📦', title: 'Package Manager', description: 'Universal package management with dependency resolution and caching.' },
          { icon: '🐳', title: 'Docker Native', description: 'First-class Docker support with automatic multi-stage builds.' },
          { icon: '📝', title: 'Auto Docs', description: 'Generate beautiful API documentation from your code comments.' },
        ],
        columns: 3,
      }),
      s('testimonials', 'Loved by Developers', 'From indie hackers to Fortune 500 engineering teams', {
        title: 'Loved by Developers',
        subtitle: 'From indie hackers to Fortune 500 engineering teams',
        testimonials: [
          { quote: 'This tool cut our CI/CD pipeline time from 45 minutes to 8 minutes. Absolutely essential for our team.', name: 'Mike Chen', role: 'Staff Engineer, BigTech Co.', rating: 5 },
          { quote: 'The DX is incredible. Everything just works out of the box. Best developer tool I\'ve used this decade.', name: 'Sarah Dev', role: 'Open Source Maintainer', rating: 5 },
        ],
      }),
      s('pricing', 'Developer Pricing', 'Free for open source. Pay as you grow.', {
        title: 'Developer Pricing',
        subtitle: 'Free for open source. Pay as you grow.',
        plans: [
          { name: 'Hobby', price: '$0', period: '/month', features: ['Unlimited personal projects', 'CLI access', 'Community support', 'Basic analytics'], highlighted: false, ctaText: 'Install Now' },
          { name: 'Team', price: '$19', period: '/user/month', features: ['Unlimited team projects', 'CI/CD integration', 'Priority support', 'Advanced analytics', 'SSO', 'Audit logs'], highlighted: true, ctaText: 'Start Free Trial' },
          { name: 'Enterprise', price: 'Custom', period: '', features: ['Everything in Team', 'On-premise', 'SLA 99.99%', 'Dedicated support', 'Custom integrations'], highlighted: false, ctaText: 'Talk to Us' },
        ],
      }),
      s('cta', 'Ready to 10x Your Productivity?', 'Install in 30 seconds. No credit card required.', {
        title: 'Ready to 10x Your Productivity?',
        subtitle: 'Install in 30 seconds. No credit card required.',
        ctaText: 'npm install @devtools/cli',
        ctaLink: '#',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Docs', url: '#' },
      { label: 'Pricing', url: '#pricing' },
      { label: 'GitHub', url: '#' },
    ],
    footerColumns: [
      { title: 'Product', links: [{ label: 'CLI', url: '#' }, { label: 'API', url: '#' }, { label: 'SDKs', url: '#' }, { label: 'Pricing', url: '#pricing' }] },
      { title: 'Resources', links: [{ label: 'Documentation', url: '#' }, { label: 'Examples', url: '#' }, { label: 'Blog', url: '#' }, { label: 'Status', url: '#' }] },
      { title: 'Community', links: [{ label: 'GitHub', url: '#' }, { label: 'Discord', url: '#' }, { label: 'Twitter', url: '#' }] },
    ],
    copyrightText: 'Dev Tools. All rights reserved.',
    socialLinks: [
      { platform: 'github', url: '#' },
      { platform: 'twitter', url: '#' },
    ],
  },

  // ─── RESTAURANT / FOOD ────────────────────────────────────
  {
    id: 'restaurant-elegant',
    name: 'Restaurant Elegant',
    category: 'restaurant',
    description: 'Restaurante de alta cocina con diseño sofisticado. Secciones de menú, galería de platos, reservas y testimonios.',
    primaryColor: '#78350F',
    secondaryColor: '#92400E',
    accentColor: '#D97706',
    backgroundColor: '#FFFBEB',
    textColor: '#1F2937',
    headingFont: 'Playfair Display',
    bodyFont: 'Lato',
    borderRadius: 4,
    themeName: 'Restaurant Elegant',
    themeSlug: 'restaurant-elegant',
    themeDescription: 'Fine dining restaurant WordPress theme by PageForge',
    sections: [
      s('hero', 'A Culinary Experience Like No Other', 'Farm-to-table fine dining in an intimate, candlelit setting', {
        title: 'A Culinary Experience Like No Other',
        subtitle: 'Farm-to-table fine dining in an intimate, candlelit setting',
        ctaText: 'Reserve a Table',
        ctaLink: '#contact',
        secondaryCtaText: 'View Menu',
        secondaryCtaLink: '#gallery',
        backgroundImage: '/templates/hero-restaurant.png',
        overlayOpacity: 0.5,
      }),
      s('about', 'Our Story', 'Established in 2015, our kitchen celebrates the finest local and seasonal ingredients', {
        title: 'Our Story',
        subtitle: 'Established in 2015, our kitchen celebrates the finest local and seasonal ingredients',
        image: '/templates/hero-restaurant.png',
        stats: [
          { value: '15+', label: 'Years of Tradition' },
          { value: '3', label: 'Michelin Stars' },
          { value: '50K+', label: 'Guests Served' },
          { value: '100%', label: 'Local Sourced' },
        ],
      }),
      s('gallery', 'Our Signature Dishes', 'A visual journey through our seasonal menu', {
        title: 'Our Signature Dishes',
        subtitle: 'A visual journey through our seasonal menu',
        images: [
          { src: '/templates/gallery-creative-1.png', alt: 'Wagyu Steak', caption: 'Wagyu A5 — Grilled to Perfection' },
          { src: '/templates/gallery-creative-2.png', alt: 'Lobster Bisque', caption: 'Maine Lobster Bisque' },
          { src: '/templates/gallery-creative-3.png', alt: 'Truffle Risotto', caption: 'Black Truffle Risotto' },
          { src: '/templates/gallery-creative-4.png', alt: 'Chocolate Soufflé', caption: 'Valrhona Chocolate Soufflé' },
          { src: '/templates/gallery-creative-5.png', alt: 'Oysters', caption: 'Fresh Oyster Selection' },
          { src: '/templates/gallery-creative-6.png', alt: 'Garden Salad', caption: 'Heirloom Tomato Garden Salad' },
        ],
        columns: 3,
      }),
      s('testimonials', 'Guest Reviews', 'What our guests say about their experience', {
        title: 'Guest Reviews',
        subtitle: 'What our guests say about their experience',
        testimonials: [
          { quote: 'An absolutely unforgettable dining experience. The tasting menu was a masterpiece from start to finish.', name: 'Robert Chen', role: 'Food Critic, Fine Dining Magazine', rating: 5 },
          { quote: 'The ambiance, the service, the food — everything was perfect. This is fine dining at its absolute best.', name: 'Maria Santos', role: 'Verified Guest', rating: 5 },
        ],
      }),
      s('faq', 'Information', 'Everything you need to know before your visit', {
        title: 'Information',
        subtitle: 'Everything you need to know before your visit',
        items: [
          { question: 'What are your opening hours?', answer: 'Tuesday to Saturday: 6:00 PM – 11:00 PM. Sunday Brunch: 11:00 AM – 3:00 PM. Closed Monday.' },
          { question: 'Do I need a reservation?', answer: 'Reservations are highly recommended, especially for Friday and Saturday evenings. Book at least 2 weeks in advance.' },
          { question: 'Do you accommodate dietary restrictions?', answer: 'Absolutely! We offer vegetarian, vegan, gluten-free, and allergy-friendly options. Please inform us when booking.' },
        ],
      }),
      s('contact', 'Reservations', 'Book your table today', {
        title: 'Reservations',
        subtitle: 'Book your table today',
        email: 'reservations@restaurant.com',
        phone: '+1 (555) 111-2222',
        address: '42 Culinary Lane, Manhattan, New York, NY',
        showForm: true,
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Menu', url: '#gallery' },
      { label: 'About', url: '#about' },
      { label: 'Reviews', url: '#testimonials' },
      { label: 'Reserve', url: '#contact' },
    ],
    footerColumns: [
      { title: 'Restaurant', links: [{ label: 'Our Story', url: '#about' }, { label: 'Menu', url: '#gallery' }, { label: 'Private Events', url: '#' }, { label: 'Gift Cards', url: '#' }] },
      { title: 'Visit', links: [{ label: 'Reservations', url: '#contact' }, { label: 'Directions', url: '#contact' }, { label: 'Parking', url: '#' }] },
      { title: 'Connect', links: [{ label: 'Instagram', url: '#' }, { label: 'Facebook', url: '#' }, { label: 'TripAdvisor', url: '#' }] },
    ],
    copyrightText: 'Restaurant Elegant. All rights reserved.',
    socialLinks: [
      { platform: 'instagram', url: '#' },
      { platform: 'facebook', url: '#' },
    ],
  },

  // ─── MEDICAL / HEALTH ─────────────────────────────────────
  {
    id: 'medical-clinic',
    name: 'Medical Clinic',
    category: 'medical',
    description: 'Clínica médica profesional con diseño confiable. Especialidades, equipo médico, testimonios de pacientes y contacto con formulario.',
    primaryColor: '#0F766E',
    secondaryColor: '#115E59',
    accentColor: '#F97316',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    headingFont: 'Montserrat',
    bodyFont: 'Open Sans',
    borderRadius: 8,
    themeName: 'Medical Clinic',
    themeSlug: 'medical-clinic',
    themeDescription: 'Professional medical clinic WordPress theme by PageForge',
    sections: [
      s('hero', 'Your Health, Our Priority', 'Compassionate care backed by years of medical excellence', {
        title: 'Your Health, Our Priority',
        subtitle: 'Compassionate care backed by years of medical excellence',
        ctaText: 'Book Appointment',
        ctaLink: '#contact',
        secondaryCtaText: 'Our Services',
        secondaryCtaLink: '#services',
        backgroundImage: '/templates/hero-medical.png',
        overlayOpacity: 0.6,
      }),
      s('services', 'Our Specialties', 'Comprehensive healthcare services for you and your family', {
        title: 'Our Specialties',
        subtitle: 'Comprehensive healthcare services for you and your family',
        items: [
          { icon: '❤️', title: 'Cardiology', description: 'Advanced cardiac care with state-of-the-art diagnostic imaging.' },
          { icon: '🧠', title: 'Neurology', description: 'Expert neurological evaluation and treatment plans.' },
          { icon: '🦴', title: 'Orthopedics', description: 'Joint, bone, and muscle care including sports medicine.' },
          { icon: '👶', title: 'Pediatrics', description: 'Compassionate care for children from newborns to teens.' },
          { icon: '👁️', title: 'Ophthalmology', description: 'Complete eye care from routine exams to surgical procedures.' },
          { icon: '🦷', title: 'Dermatology', description: 'Skin health, cosmetic dermatology, and laser treatments.' },
        ],
        columns: 3,
      }),
      s('about', 'About Our Clinic', 'Serving our community with exceptional medical care since 2005', {
        title: 'About Our Clinic',
        subtitle: 'Serving our community with exceptional medical care since 2005',
        image: '/templates/hero-medical.png',
        stats: [
          { value: '20+', label: 'Years Serving' },
          { value: '30+', label: 'Specialists' },
          { value: '100K+', label: 'Patients Treated' },
          { value: '15', label: 'Departments' },
        ],
      }),
      s('team', 'Our Medical Team', 'Board-certified physicians dedicated to your well-being', {
        title: 'Our Medical Team',
        subtitle: 'Board-certified physicians dedicated to your well-being',
        members: [
          { name: 'Dr. Sarah Mitchell', role: 'Medical Director', bio: 'Board-certified internist with 25 years of experience in clinical medicine.', avatar: '/templates/avatar-medical-1.png', socials: [] },
          { name: 'Dr. James Rodriguez', role: 'Chief of Surgery', bio: 'Fellowship-trained surgeon specializing in minimally invasive procedures.', avatar: '/templates/avatar-medical-2.png', socials: [] },
          { name: 'Dr. Priya Sharma', role: 'Head of Pediatrics', bio: 'Pediatric specialist with a passion for children\'s health and development.', avatar: '/templates/avatar-medical-3.png', socials: [] },
        ],
      }),
      s('testimonials', 'Patient Testimonials', 'Real stories from our patients', {
        title: 'Patient Testimonials',
        subtitle: 'Real stories from our patients',
        testimonials: [
          { quote: 'The entire team made me feel comfortable and cared for. Dr. Mitchell is truly exceptional.', name: 'Patricia Williams', role: 'Patient', rating: 5 },
          { quote: 'After visiting several clinics, I finally found one that treats me like family. Highly recommended.', name: 'Michael Torres', role: 'Patient', rating: 5 },
        ],
      }),
      s('cta', 'Need to See a Doctor?', 'Schedule your appointment today — same-day appointments available', {
        title: 'Need to See a Doctor?',
        subtitle: 'Schedule your appointment today — same-day appointments available',
        ctaText: 'Book Appointment',
        ctaLink: '#contact',
      }),
      s('contact', 'Contact & Appointments', 'We\'re here to help', {
        title: 'Contact & Appointments',
        subtitle: 'We\'re here to help',
        email: 'info@medicalclinic.com',
        phone: '+1 (555) 000-1234',
        address: '200 Health Boulevard, Suite 300, Houston, TX 77001',
        showForm: true,
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Services', url: '#services' },
      { label: 'About', url: '#about' },
      { label: 'Doctors', url: '#team' },
      { label: 'Contact', url: '#contact' },
    ],
    footerColumns: [
      { title: 'Services', links: [{ label: 'Cardiology', url: '#services' }, { label: 'Neurology', url: '#services' }, { label: 'Orthopedics', url: '#services' }, { label: 'Pediatrics', url: '#services' }] },
      { title: 'Clinic', links: [{ label: 'About Us', url: '#about' }, { label: 'Our Team', url: '#team' }, { label: 'Careers', url: '#' }] },
      { title: 'Patient Info', links: [{ label: 'Insurance', url: '#' }, { label: 'Patient Portal', url: '#' }, { label: 'Billing', url: '#' }] },
    ],
    copyrightText: 'Medical Clinic. All rights reserved.',
    socialLinks: [
      { platform: 'facebook', url: '#' },
      { platform: 'instagram', url: '#' },
      { platform: 'linkedin', url: '#' },
    ],
  },

  // ─── EDUCATION / LMS ───────────────────────────────────────
  {
    id: 'education-academy',
    name: 'Online Academy',
    category: 'education',
    description: 'Academia online con diseño moderno. Catálogo de cursos, instructores, precios y testimonios de estudiantes.',
    primaryColor: '#4F46E5',
    secondaryColor: '#7C3AED',
    accentColor: '#F59E0B',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    headingFont: 'Poppins',
    bodyFont: 'Open Sans',
    borderRadius: 10,
    themeName: 'Online Academy',
    themeSlug: 'online-academy',
    themeDescription: 'Modern online academy WordPress theme by PageForge',
    sections: [
      s('hero', 'Learn From the Best, Anywhere', 'World-class courses taught by industry experts. Start learning today.', {
        title: 'Learn From the Best, Anywhere',
        subtitle: 'World-class courses taught by industry experts. Start learning today.',
        ctaText: 'Browse Courses',
        ctaLink: '#services',
        secondaryCtaText: 'How It Works',
        secondaryCtaLink: '#about',
        backgroundImage: '/templates/hero-education.png',
        overlayOpacity: 0.6,
      }),
      s('features', 'Why Choose Our Academy', 'A learning experience designed for success', {
        title: 'Why Choose Our Academy',
        subtitle: 'A learning experience designed for success',
        items: [
          { icon: '🎓', title: 'Certified Courses', description: 'Earn recognized certificates upon completion of each course.' },
          { icon: '📱', title: 'Learn Anywhere', description: 'Access courses on any device — desktop, tablet, or mobile.' },
          { icon: '💬', title: 'Live Sessions', description: 'Interactive live classes with real-time Q&A and discussions.' },
          { icon: '🏆', title: 'Expert Instructors', description: 'Learn from professionals with real-world industry experience.' },
        ],
        columns: 2,
      }),
      s('services', 'Popular Courses', 'Enroll in our most in-demand programs', {
        title: 'Popular Courses',
        subtitle: 'Enroll in our most in-demand programs',
        items: [
          { icon: '💻', title: 'Full-Stack Web Development', description: 'Comprehensive 12-week program covering HTML, CSS, JavaScript, React, Node.js and more.' },
          { icon: '📊', title: 'Data Science & AI', description: 'Master Python, machine learning, deep learning, and data visualization.' },
          { icon: '🎨', title: 'UX/UI Design', description: 'Learn design thinking, Figma, prototyping, and user research methodologies.' },
          { icon: '📈', title: 'Digital Marketing', description: 'SEO, SEM, social media marketing, analytics, and growth strategies.' },
          { icon: '📱', title: 'Mobile App Development', description: 'Build iOS and Android apps with React Native and Flutter.' },
          { icon: '☁️', title: 'Cloud Computing', description: 'AWS, Azure, and GCP certifications with hands-on labs.' },
        ],
        columns: 3,
      }),
      s('stats', 'Our Numbers', '', {
        items: [
          { icon: '📚', value: '200+', label: 'Courses' },
          { icon: '👨‍🎓', value: '50K+', label: 'Students' },
          { icon: '👨‍🏫', value: '80+', label: 'Instructors' },
          { icon: '🏆', value: '95%', label: 'Satisfaction Rate' },
        ],
      }),
      s('testimonials', 'Student Success Stories', 'See what our students have achieved', {
        title: 'Student Success Stories',
        subtitle: 'See what our students have achieved',
        testimonials: [
          { quote: 'After completing the Full-Stack program, I landed my dream job as a software engineer at a top tech company.', name: 'Andrea López', role: 'Software Engineer, Google', rating: 5 },
          { quote: 'The Data Science course gave me the skills and confidence to transition my career into AI. Life-changing experience.', name: 'Marcus Johnson', role: 'Data Scientist, Meta', rating: 5 },
        ],
      }),
      s('pricing', 'Plans & Pricing', 'Choose the plan that fits your goals', {
        title: 'Plans & Pricing',
        subtitle: 'Choose the plan that fits your goals',
        plans: [
          { name: 'Single Course', price: '$49', period: '/course', features: ['One course access', 'Certificate', 'Lifetime access', 'Community forum'], highlighted: false, ctaText: 'Enroll Now' },
          { name: 'Pro Membership', price: '$29', period: '/month', features: ['All courses', 'Certificates', 'Live sessions', 'Mentorship', 'Projects portfolio'], highlighted: true, ctaText: 'Start Learning' },
          { name: 'Team Plan', price: '$19', period: '/user/month', features: ['Everything in Pro', 'Team dashboard', 'Progress tracking', 'Admin controls', 'Priority support'], highlighted: false, ctaText: 'Contact Sales' },
        ],
      }),
      s('cta', 'Start Learning Today', 'Join 50,000+ students already advancing their careers', {
        title: 'Start Learning Today',
        subtitle: 'Join 50,000+ students already advancing their careers',
        ctaText: 'Browse Free Courses',
        ctaLink: '#services',
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Courses', url: '#services' },
      { label: 'Pricing', url: '#pricing' },
      { label: 'About', url: '#about' },
    ],
    footerColumns: [
      { title: 'Academy', links: [{ label: 'About Us', url: '#about' }, { label: 'Careers', url: '#' }, { label: 'Blog', url: '#' }, { label: 'Affiliates', url: '#' }] },
      { title: 'Courses', links: [{ label: 'Web Development', url: '#' }, { label: 'Data Science', url: '#' }, { label: 'Design', url: '#' }, { label: 'Marketing', url: '#' }] },
      { title: 'Support', links: [{ label: 'Help Center', url: '#' }, { label: 'Contact', url: '#' }, { label: 'FAQ', url: '#' }] },
    ],
    copyrightText: 'Online Academy. All rights reserved.',
    socialLinks: [
      { platform: 'twitter', url: '#' },
      { platform: 'facebook', url: '#' },
      { platform: 'instagram', url: '#' },
      { platform: 'youtube', url: '#' },
    ],
  },

  // ─── REAL ESTATE ───────────────────────────────────────────
  {
    id: 'realestate-agency',
    name: 'Real Estate Agency',
    category: 'realestate',
    description: 'Inmobiliaria profesional con búsqueda de propiedades, agentes destacados, testimonios y formulario de contacto.',
    primaryColor: '#1F2937',
    secondaryColor: '#374151',
    accentColor: '#059669',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    headingFont: 'Montserrat',
    bodyFont: 'Open Sans',
    borderRadius: 6,
    themeName: 'Real Estate Agency',
    themeSlug: 'real-estate-agency',
    themeDescription: 'Professional real estate agency WordPress theme by PageForge',
    sections: [
      s('hero', 'Find Your Dream Home', 'Premium properties in the most sought-after neighborhoods', {
        title: 'Find Your Dream Home',
        subtitle: 'Premium properties in the most sought-after neighborhoods',
        ctaText: 'Browse Properties',
        ctaLink: '#gallery',
        secondaryCtaText: 'Contact an Agent',
        secondaryCtaLink: '#contact',
        backgroundImage: '/templates/hero-realestate.png',
        overlayOpacity: 0.55,
      }),
      s('features', 'Why Choose Us', 'A seamless real estate experience', {
        title: 'Why Choose Us',
        subtitle: 'A seamless real estate experience',
        items: [
          { icon: '🏘️', title: 'Premium Listings', description: 'Curated selection of luxury properties and exclusive developments.' },
          { icon: '📸', title: 'Virtual Tours', description: 'Immersive 360° virtual tours of every listed property.' },
          { icon: '💰', title: 'Best Market Prices', description: 'Expert negotiation to get you the best deal possible.' },
          { icon: '📋', title: 'Full Legal Support', description: 'Complete legal assistance from offer to closing.' },
        ],
        columns: 2,
      }),
      s('gallery', 'Featured Properties', 'Explore our exclusive property listings', {
        title: 'Featured Properties',
        subtitle: 'Explore our exclusive property listings',
        images: [
          { src: '/templates/gallery-creative-1.png', alt: 'Luxury Villa', caption: 'Ocean View Villa — 4BR/3BA — $2,450,000' },
          { src: '/templates/gallery-creative-2.png', alt: 'Modern Penthouse', caption: 'Downtown Penthouse — 3BR/2BA — $1,890,000' },
          { src: '/templates/gallery-creative-3.png', alt: 'Family Home', caption: 'Garden District Home — 5BR/4BA — $875,000' },
          { src: '/templates/gallery-creative-4.png', alt: 'Beach Condo', caption: 'Beachfront Condo — 2BR/2BA — $650,000' },
          { src: '/templates/gallery-creative-5.png', alt: 'Mountain Cabin', caption: 'Mountain Retreat — 3BR/2BA — $520,000' },
          { src: '/templates/gallery-creative-6.png', alt: 'City Loft', caption: 'Arts District Loft — 1BR/1BA — $425,000' },
        ],
        columns: 3,
      }),
      s('stats', 'Our Track Record', '', {
        items: [
          { icon: '🏠', value: '2,500+', label: 'Properties Sold' },
          { icon: '🤝', value: '1,800+', label: 'Happy Families' },
          { icon: '💰', value: '$2B+', label: 'Total Sales Volume' },
          { icon: '⭐', value: '4.9/5', label: 'Client Rating' },
        ],
      }),
      s('testimonials', 'Happy Homeowners', 'Stories from families we\'ve helped find their dream homes', {
        title: 'Happy Homeowners',
        subtitle: 'Stories from families we\'ve helped find their dream homes',
        testimonials: [
          { quote: 'Our agent made the entire process seamless. From our first viewing to closing day, we felt supported every step.', name: 'The Johnson Family', role: 'Homeowners since 2023', rating: 5 },
          { quote: 'We found our dream beach condo within 2 weeks. The virtual tour feature saved us so much time.', name: 'Maria & David', role: 'Homeowners since 2024', rating: 5 },
        ],
      }),
      s('team', 'Our Agents', 'Meet our experienced real estate professionals', {
        title: 'Our Agents',
        subtitle: 'Meet our experienced real estate professionals',
        members: [
          { name: 'Amanda Richardson', role: 'Senior Agent', bio: '15+ years in luxury real estate. Top producer for 8 consecutive years.', avatar: '/templates/avatar-realestate-1.png', socials: [{ platform: 'linkedin', url: '#' }] },
          { name: 'Carlos Vega', role: 'Property Specialist', bio: 'Expert in residential properties with deep market knowledge.', avatar: '/templates/avatar-realestate-2.png', socials: [{ platform: 'linkedin', url: '#' }] },
          { name: 'Jennifer Park', role: 'Commercial Agent', bio: 'Specializing in commercial and investment properties.', avatar: '/templates/avatar-realestate-3.png', socials: [{ platform: 'linkedin', url: '#' }] },
        ],
      }),
      s('cta', 'Ready to Find Your Perfect Home?', 'Let our expert agents guide you through every step', {
        title: 'Ready to Find Your Perfect Home?',
        subtitle: 'Let our expert agents guide you through every step',
        ctaText: 'Schedule a Consultation',
        ctaLink: '#contact',
      }),
      s('contact', 'Get In Touch', 'We\'re here to help you find the perfect property', {
        title: 'Get In Touch',
        subtitle: 'We\'re here to help you find the perfect property',
        email: 'info@realestateagency.com',
        phone: '+1 (555) 789-0123',
        address: '100 Commerce Blvd, Suite 500, Miami, FL 33101',
        showForm: true,
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Properties', url: '#gallery' },
      { label: 'Agents', url: '#team' },
      { label: 'About', url: '#about' },
      { label: 'Contact', url: '#contact' },
    ],
    footerColumns: [
      { title: 'Properties', links: [{ label: 'Residential', url: '#' }, { label: 'Commercial', url: '#' }, { label: 'Luxury', url: '#' }, { label: 'New Developments', url: '#' }] },
      { title: 'Company', links: [{ label: 'About Us', url: '#about' }, { label: 'Our Agents', url: '#team' }, { label: 'Testimonials', url: '#testimonials' }] },
      { title: 'Contact', links: [{ label: 'Office Location', url: '#contact' }, { label: 'Phone', url: '#contact' }, { label: 'Email', url: '#contact' }] },
    ],
    copyrightText: 'Real Estate Agency. All rights reserved.',
    socialLinks: [
      { platform: 'facebook', url: '#' },
      { platform: 'instagram', url: '#' },
      { platform: 'linkedin', url: '#' },
    ],
  },

  // ─── LAWYER / LEGAL ───────────────────────────────────────
  {
    id: 'legal-firm',
    name: 'Legal Firm',
    category: 'legal',
    description: 'Firma de abogados con diseño profesional y confiable. Áreas de práctica, equipo de abogados, casos de éxito y consulta.',
    primaryColor: '#1E3A5F',
    secondaryColor: '#2C5282',
    accentColor: '#C9A84C',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    headingFont: 'Montserrat',
    bodyFont: 'Open Sans',
    borderRadius: 4,
    themeName: 'Legal Firm',
    themeSlug: 'legal-firm',
    themeDescription: 'Professional law firm WordPress theme by PageForge',
    sections: [
      s('hero', 'Experienced Legal Representation', 'Protecting your rights with integrity, expertise, and dedication', {
        title: 'Experienced Legal Representation',
        subtitle: 'Protecting your rights with integrity, expertise, and dedication',
        ctaText: 'Free Consultation',
        ctaLink: '#contact',
        secondaryCtaText: 'Our Practice Areas',
        secondaryCtaLink: '#services',
        backgroundImage: '/templates/hero-legal.png',
        overlayOpacity: 0.65,
      }),
      s('services', 'Practice Areas', 'Comprehensive legal services tailored to your needs', {
        title: 'Practice Areas',
        subtitle: 'Comprehensive legal services tailored to your needs',
        items: [
          { icon: '⚖️', title: 'Corporate Law', description: 'Business formation, mergers, acquisitions, and corporate governance.' },
          { icon: '🏠', title: 'Real Estate Law', description: 'Property transactions, disputes, landlord-tenant, and zoning.' },
          { icon: '👨‍👩‍👧', title: 'Family Law', description: 'Divorce, child custody, adoption, and domestic matters.' },
          { icon: '💼', title: 'Personal Injury', description: 'Accidents, medical malpractice, and wrongful death cases.' },
          { icon: '📊', title: 'Tax Law', description: 'Tax planning, disputes, compliance, and international taxation.' },
          { icon: '🛡️', title: 'Criminal Defense', description: 'DUI, drug offenses, white-collar crime, and federal defense.' },
        ],
        columns: 3,
      }),
      s('about', 'About the Firm', 'Over 25 years of delivering results for our clients', {
        title: 'About the Firm',
        subtitle: 'Over 25 years of delivering results for our clients',
        image: '/templates/hero-legal.png',
        stats: [
          { value: '25+', label: 'Years Experience' },
          { value: '5,000+', label: 'Cases Handled' },
          { value: '95%', label: 'Success Rate' },
          { value: '$500M+', label: 'Recoveries Won' },
        ],
      }),
      s('team', 'Our Attorneys', 'Dedicated legal professionals fighting for you', {
        title: 'Our Attorneys',
        subtitle: 'Dedicated legal professionals fighting for you',
        members: [
          { name: 'Robert Blackwell, Esq.', role: 'Founding Partner', bio: 'Harvard Law graduate with 30+ years of trial experience in corporate and civil litigation.', avatar: '/templates/avatar-legal-1.png', socials: [{ platform: 'linkedin', url: '#' }] },
          { name: 'Sarah Mitchell, Esq.', role: 'Senior Partner', bio: 'Specializes in family law with a reputation for compassionate and effective advocacy.', avatar: '/templates/avatar-legal-2.png', socials: [{ platform: 'linkedin', url: '#' }] },
          { name: 'David Chen, Esq.', role: 'Partner', bio: 'Former prosecutor turned defense attorney. 98% acquittal rate in criminal cases.', avatar: '/templates/avatar-legal-3.png', socials: [{ platform: 'linkedin', url: '#' }] },
        ],
      }),
      s('testimonials', 'Client Testimonials', 'Hear from the clients we\'ve helped', {
        title: 'Client Testimonials',
        subtitle: 'Hear from the clients we\'ve helped',
        testimonials: [
          { quote: 'The team at this firm fought relentlessly for our case. Their expertise and dedication resulted in a life-changing settlement.', name: 'James & Mary Patterson', role: 'Clients', rating: 5 },
          { quote: 'Professional, knowledgeable, and truly caring. They guided me through the most difficult time of my life with compassion.', name: 'Linda Rodriguez', role: 'Client', rating: 5 },
        ],
      }),
      s('faq', 'Legal FAQ', 'Common questions about our legal services', {
        title: 'Legal FAQ',
        subtitle: 'Common questions about our legal services',
        items: [
          { question: 'Do you offer free initial consultations?', answer: 'Yes, we offer a free 30-minute initial consultation for all new clients. This helps us understand your situation and advise on next steps.' },
          { question: 'What are your fees?', answer: 'We offer various fee arrangements including hourly rates, flat fees, and contingency fees depending on the type of case. This will be discussed during your consultation.' },
          { question: 'How long does a typical case take?', answer: 'The duration varies depending on the complexity of the case. We\'ll provide a realistic timeline during your initial consultation and keep you updated throughout.' },
        ],
      }),
      s('cta', 'Need Legal Help?', 'Schedule a free consultation with one of our experienced attorneys', {
        title: 'Need Legal Help?',
        subtitle: 'Schedule a free consultation with one of our experienced attorneys',
        ctaText: 'Schedule Free Consultation',
        ctaLink: '#contact',
      }),
      s('contact', 'Contact Us', 'We\'re ready to fight for your rights', {
        title: 'Contact Us',
        subtitle: 'We\'re ready to fight for your rights',
        email: 'info@legalfirm.com',
        phone: '+1 (555) 333-4444',
        address: '500 Justice Avenue, Suite 1200, Washington, DC 20001',
        showForm: true,
      }),
    ],
    navItems: [
      { label: 'Home', url: '/' },
      { label: 'Practice Areas', url: '#services' },
      { label: 'About', url: '#about' },
      { label: 'Attorneys', url: '#team' },
      { label: 'Contact', url: '#contact' },
    ],
    footerColumns: [
      { title: 'Practice Areas', links: [{ label: 'Corporate Law', url: '#services' }, { label: 'Family Law', url: '#services' }, { label: 'Personal Injury', url: '#services' }, { label: 'Criminal Defense', url: '#services' }] },
      { title: 'Firm', links: [{ label: 'About Us', url: '#about' }, { label: 'Our Attorneys', url: '#team' }, { label: 'Results', url: '#' }] },
      { title: 'Contact', links: [{ label: 'Office Location', url: '#contact' }, { label: 'Phone', url: '#contact' }, { label: 'Email', url: '#contact' }] },
    ],
    copyrightText: 'Legal Firm. All rights reserved.',
    socialLinks: [
      { platform: 'linkedin', url: '#' },
      { platform: 'facebook', url: '#' },
      { platform: 'twitter', url: '#' },
    ],
  },
];

export default templates;
