import { NextResponse } from 'next/server';

/**
 * Default theme configuration used as a starting point for new themes.
 * Mirrors the PageTheme shape from builder-types.ts.
 */
const DEFAULT_THEME_CONFIG = {
  name: 'My WordPress Theme',
  slug: 'my-theme',
  description: 'A professional WordPress theme generated by PageForge',
  version: '1.0.0',
  author: 'PageForge',
  authorUri: 'https://pageforge.dev',
  license: 'GPL-2.0-or-later',
  licenseUri: 'https://www.gnu.org/licenses/gpl-2.0.html',
  textDomain: 'my-theme',
  tags: 'one-column, custom-menu, featured-images, threaded-comments, translation-ready',
  template: 'landing' as const,
  theme: {
    primaryColor: '#2563EB',
    secondaryColor: '#7C3AED',
    accentColor: '#F59E0B',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    borderRadius: 'medium' as const,
    style: 'modern' as const,
  },
  sections: [
    { type: 'hero', enabled: true },
    { type: 'features', enabled: true },
    { type: 'about', enabled: true },
    { type: 'testimonials', enabled: true },
    { type: 'cta', enabled: true },
    { type: 'footer', enabled: true },
  ],
};

/**
 * GET /api/generate-theme-schema
 *
 * Returns the ThemeConfig schema so the frontend knows what fields
 * to send when calling POST /api/generate-theme.
 */
export async function GET() {
  return NextResponse.json({
    schema: {
      // --- Theme Identity ---
      name:           { type: 'string',  required: true,  label: 'Theme Name',        description: 'Display name of the theme (shown in WP admin)' },
      slug:           { type: 'string',  required: true,  label: 'Theme Slug',         description: 'Machine-readable identifier (lowercase, hyphens)' },
      description:    { type: 'string',  required: false, label: 'Description',        description: 'Brief description of the theme' },
      version:        { type: 'string',  required: false, label: 'Version',            description: 'Semantic version', default: '1.0.0' },
      author:         { type: 'string',  required: false, label: 'Author',             description: 'Theme author name', default: 'PageForge' },
      authorUri:      { type: 'string',  required: false, label: 'Author URI',         description: 'Author website URL' },
      license:        { type: 'string',  required: false, label: 'License',            description: 'License identifier', default: 'GPL-2.0-or-later' },
      licenseUri:     { type: 'string',  required: false, label: 'License URI',        description: 'Link to license text' },
      textDomain:     { type: 'string',  required: false, label: 'Text Domain',        description: 'Translation text domain (defaults to slug)' },
      tags:           { type: 'string',  required: false, label: 'Tags',               description: 'Comma-separated WordPress.org tags' },

      // --- Template ---
      template:       { type: 'string',  required: false, label: 'Template Type',      description: 'Base template for the theme' },

      // --- Theme Styling ---
      theme: {
        type: 'object',
        required: false,
        label: 'Theme Styling',
        description: 'Visual style configuration',
        properties: {
          primaryColor:   { type: 'string', required: false, label: 'Primary Color',    default: '#2563EB' },
          secondaryColor: { type: 'string', required: false, label: 'Secondary Color',  default: '#7C3AED' },
          accentColor:    { type: 'string', required: false, label: 'Accent Color',     default: '#F59E0B' },
          backgroundColor:{ type: 'string', required: false, label: 'Background Color', default: '#FFFFFF' },
          textColor:      { type: 'string', required: false, label: 'Text Color',       default: '#1F2937' },
          headingFont:    { type: 'string', required: false, label: 'Heading Font',     default: 'Inter' },
          bodyFont:       { type: 'string', required: false, label: 'Body Font',        default: 'Inter' },
          borderRadius:   { type: 'string', required: false, label: 'Border Radius',    default: 'medium', enum: ['none', 'small', 'medium', 'large', 'full'] },
          style:          { type: 'string', required: false, label: 'Design Style',     default: 'modern', enum: ['modern', 'classic', 'minimal', 'bold'] },
        },
      },

      // --- Sections ---
      sections: { type: 'array', required: false, label: 'Sections', description: 'Array of section objects with type and enabled flag' },
    },
    sectionTypes: [
      'hero',
      'about',
      'services',
      'features',
      'testimonials',
      'pricing',
      'cta',
      'contact',
      'gallery',
      'faq',
      'stats',
      'team',
      'blog_posts',
      'navbar',
      'footer',
    ],
    templateTypes: [
      'landing',
      'portfolio',
      'restaurant',
      'saas',
      'agency',
      'ecommerce',
      'blog',
    ],
    defaultConfig: DEFAULT_THEME_CONFIG,
  });
}
